name: Build CARET

on:
  schedule:
    - cron: 0 17 * * * # run at 2 AM JST
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ros_distro: [humble, iron]
        # ros_distro: [humble, iron, jazzy]

    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}

    steps:
      - uses: actions/checkout@v5

      - name: Clean up disk space
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet

      - name: setup virtual env(only for Jazzy)
        run: |
          set -e

          if [[ "${{ matrix.ros_distro }}" == "jazzy" ]]; then
            sudo apt install python3-pip
            sudo apt-get install python3-virtualenv

            virtualenv -p python3 --system-site-packages ./venv/jazzy
            . ./venv/jazzy/bin/activate
          fi

      - name: setup CARET
        run: |
          mkdir src && \
          vcs import src < caret.repos && \
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh && \
          ./setup_caret.sh -c -d ${{ matrix.ros_distro }}

      - name: Build CARET
        shell: bash
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.bash
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
